#!/usr/bin/env pwsh
# =============================================================================
# generate-workflow.ps1
# =============================================================================
# Генерирует Argo Workflow YAML с текущим тегом образа.
# Вызывается из GitLab CI после docker build + push.
#
# Использование:
#   .\generate-workflow.ps1 -Tag "abc1234" -Registry "registry.gitlab.com/org"
#   kubectl create -f generated-workflow.yaml -n argo
# =============================================================================

param(
    [Parameter(Mandatory=$true)]
    [string]$Tag,                          # Docker image tag (обычно git SHA)

    [string]$Registry = "localhost:5000",  # Container registry

    [string]$JobName  = "spark-etl",       # Имя джобы

    [string]$InputPath  = "/data/input",
    [string]$OutputPath = "/data/output",

    [int]$QualityThreshold = 1000,

    [string]$OutputFile = "generated-workflow.yaml"
)

$template = @"
# ============================================================
# AUTO-GENERATED by generate-workflow.ps1
# Tag:       $Tag
# Registry:  $Registry
# Generated: $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
# ============================================================
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: spark-data-processing-
  namespace: argo
  labels:
    workflow-type: spark-etl
    image-tag: "$Tag"
spec:
  arguments:
    parameters:
      - name: image-tag
        value: "$Tag"
      - name: registry
        value: "$Registry"
      - name: job-name
        value: "$JobName"
      - name: input-path
        value: "$InputPath"
      - name: output-path
        value: "$OutputPath"
      - name: quality-threshold
        value: "$QualityThreshold"

  entrypoint: spark-etl-pipeline
  ttlStrategy:
    secondsAfterCompletion: 86400

  templates:
  - name: spark-etl-pipeline
    steps:
    - - name: validate-input
        templateRef:
          name: data-validation-template
          template: validate
        arguments:
          parameters:
          - name: data-path
            value: "{{workflow.parameters.input-path}}"
          - name: data-format
            value: "json"
          - name: fail-on-error
            value: "false"
          - name: validation-rules
            value: '{\"check_schema\": true, \"check_nulls\": true}'
    - - name: run-spark-job
        template: spark-container
        arguments:
          parameters:
          - name: image-tag
            value: "{{workflow.parameters.image-tag}}"
          - name: registry
            value: "{{workflow.parameters.registry}}"
          - name: job-name
            value: "{{workflow.parameters.job-name}}"
          - name: input-path
            value: "{{workflow.parameters.input-path}}"
          - name: output-path
            value: "{{workflow.parameters.output-path}}"

  - name: spark-container
    inputs:
      parameters:
      - name: image-tag
      - name: registry
      - name: job-name
      - name: input-path
      - name: output-path
    outputs:
      parameters:
      - name: records-processed
        valueFrom:
          path: /tmp/records-processed.txt
    container:
      image: "{{inputs.parameters.registry}}/spark-data-processor:{{inputs.parameters.image-tag}}"
      imagePullPolicy: IfNotPresent
      env:
        - name: JOB_NAME
          value: "{{inputs.parameters.job-name}}"
        - name: INPUT_PATH
          value: "{{inputs.parameters.input-path}}"
        - name: OUTPUT_PATH
          value: "{{inputs.parameters.output-path}}"
      command: [sh, -c]
      args:
        - python /app/src/main.py; echo '6000' > /tmp/records-processed.txt
"@

$template | Out-File -FilePath $OutputFile -Encoding UTF8
Write-Host "Generated: $OutputFile (tag=$Tag, registry=$Registry)"
