apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: staging

namePrefix: staging-

commonLabels:
  env: staging

patches:
  - target:
      kind: Deployment
      name: data-ui
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: staging
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.gitlab.com/myorg/data-ui:staging

configMapGenerator:
  - name: data-ui-config
    literals:
      - ENV=staging
      - LOG_LEVEL=info
      - API_URL=http://argo-server.argo:2746
