apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: production
  creationTimestamp: null
spec:
  encryptedData:
    username: AgBm1cF3x9ABCxyz...
    password: AgC4kRp2y7DEFabc...
    host: AgD9mNt5z1GHIdef...
  template:
    metadata:
      name: db-credentials
      namespace: production
      labels:
        app: my-app
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shared-tls
  namespace: production
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    tls.crt: AgBm1cF3x9...
    tls.key: AgC4kRp2y7...
  template:
    metadata:
      name: shared-tls
      namespace: production
    type: kubernetes.io/tls

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: global-registry-credentials
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    .dockerconfigjson: AgBm1cF3x9...
  template:
    metadata:
      name: global-registry-credentials
    type: kubernetes.io/dockerconfigjson
